### ISSUE TITLE
✨[Client]: Actions Page

### ISSUE THREAD

**Issue by EduardoCastillo-Hexaware** [BladimirOrihuela-Hexaware/Talos-Help#20]
## Description
This page is the one that contains all information regarding how to use all actions in TALOS.

##Requirements

- Need to displayed all actions that are not deprecated in TALOS
- Need to have filter buttons at the top of the screen, in order to filter the actions for:
          1. All
          2. Browser
          3. Mobile 
          4. Desktop
          5. API (pending) 
- For each action card should be displayed: Action Name, Icons for supported TC types and a Description for the action.
- Need to have a link referenced to each action web page for more information.

**Comment by BladimirOrihuela-Hexaware** [comment]
For simplicity this requirement was divided in: #37 #38 #39
